export const exportAsMarkdown = (data: {
  blueprint?: any;
  bundles?: any;
  launchKit?: any;
  listingKit?: any;
  productName: string;
}): string => {
  let md = `# ${data.productName}\n\n`;
  md += `Generated by DigiStream - ${new Date().toLocaleDateString()}\n\n`;
  md += `---\n\n`;

  if (data.blueprint) {
    md += `## Product Blueprint\n\n`;
    md += `**Product Name:** ${data.blueprint.productName || data.productName}\n\n`;
    if (data.blueprint.marketingCopy?.shortDescription) {
      md += `**Description:** ${data.blueprint.marketingCopy.shortDescription}\n\n`;
    }
    if (data.blueprint.pageBreakdown) {
      md += `### Page Breakdown\n\n`;
      data.blueprint.pageBreakdown.forEach((page: any, i: number) => {
        md += `#### ${i + 1}. ${page.pageName || page.name}\n`;
        md += `${page.purpose || page.description || ''}\n\n`;
        if (page.contentSuggestions) {
          page.contentSuggestions.forEach((s: string) => md += `- ${s}\n`);
        }
        md += `\n`;
      });
    }
    if (data.blueprint.marketingCopy) {
      md += `### Marketing Copy\n\n`;
      const bullets = data.blueprint.marketingCopy.benefitBullets || data.blueprint.marketingCopy.bullets || [];
      if (bullets.length) {
        md += `**Bullets:**\n`;
        bullets.forEach((b: string) => md += `- ${b}\n`);
      }
      md += `\n`;
    }
    if (data.blueprint.styleGuide) {
      md += `### Style Guide\n\n`;
      const colors = data.blueprint.styleGuide.colors || data.blueprint.styleGuide.colorPalette || [];
      const fonts = data.blueprint.styleGuide.fonts || data.blueprint.styleGuide.fontPairings || [];
      const mood = data.blueprint.styleGuide.moodKeywords || data.blueprint.styleGuide.mood || [];
      if (colors.length) md += `- **Colors:** ${colors.join(', ')}\n`;
      if (fonts.length) md += `- **Fonts:** ${fonts.join(', ')}\n`;
      if (mood.length) md += `- **Mood:** ${mood.join(', ')}\n\n`;
    }
  }

  if (data.listingKit) {
    md += `## Listing Kit\n\n`;
    md += `### Titles\n`;
    md += `- **Primary:** ${data.listingKit.titles?.primary || ''}\n`;
    md += `- **Alt 1:** ${data.listingKit.titles?.alternative1 || ''}\n`;
    md += `- **Alt 2:** ${data.listingKit.titles?.alternative2 || ''}\n\n`;
    if (data.listingKit.etsyTags) {
      md += `### Etsy Tags\n`;
      md += data.listingKit.etsyTags.join(', ') + '\n\n';
    }
  }

  if (data.bundles) {
    md += `## Bundle Variants\n\n`;
    if (data.bundles.liteVersion) {
      md += `### Lite Version\n`;
      md += `${data.bundles.liteVersion.description || ''}\n\n`;
    }
    if (data.bundles.bonusAddOn) {
      md += `### Bonus Add-On\n`;
      md += `${data.bundles.bonusAddOn.description || ''}\n\n`;
    }
    if (data.bundles.premiumBundle) {
      md += `### Premium Bundle\n`;
      md += `${data.bundles.premiumBundle.description || ''}\n\n`;
    }
  }

  return md;
};

export const copyAllToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
};

export const downloadAsFile = (content: string, filename: string, type: string = 'text/plain') => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportAsJSON = (data: any, filename: string) => {
  const json = JSON.stringify(data, null, 2);
  downloadAsFile(json, filename, 'application/json');
};
